import { createElement } from 'lwc';
import VoucherRequest from 'c/voucherRequest';

describe('c-voucher-request', () => {
    afterEach(() => {
        
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        
        const element = createElement('c-voucher-request', {
            is: VoucherRequest
        });

        
        document.body.appendChild(element);

        
        expect(1).toBe(1);
    });
});