# This is a sanity check workflow which runs unit tests and scans the code via sonar cloud. This is run on each pull request on develop branch

name: Sanity Check

# Controls when the action will run. Workflow runs on pull request
on:
  pull_request:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs unit tests 
  run_unit_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install  
    - name: Install jq
      run: |
        sudo apt-get install jq
    - name: Populate auth file
      shell: bash
      run: 'echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt'
    - name: Authenticate Dev Hub
      run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a NessDevHub -d'
    - name: Create new scratch org
      run: |
        'sfdx force:org:create --setdefaultusername -f config/project-scratch-def.json -d 1 -setalias scratch-org'
    - name: deploy codebase to scratch org
      run: |
        'sfdx force:source:deploy -p force-app -w 140'
    - name: open scratch org
      run: |
        'sfdx force:source:open'
    - name: execute unit tests
      run: |
        'sfdx force:apex:test:run --verbose -c -r human -d testLog -w 140'
    - name: delete scratch org
      run: |
        'sfdx force:org:delete --noprompt --targetusername scratch-org'




